ifneq (,$(filter defaulttransceiver,$(USEMODULE)))
    USEMODULE += ml7396
    ifeq (,$(filter netdev_base,$(USEMODULE)))
        USEMODULE += transceiver
    endif
endif

ifneq (,$(filter ng_netif,$(USEMODULE)))
  USEMODULE += ng_ml7396
  USEMODULE += ng_nomac
  USEMODULE += auto_init_ng_netif
endif
